In [1]:
import numpy as np
from datetime import timedelta

# 1.Create a 3x3x3 array with random values

In [2]:
arr=np.random.rand(3,3,3)
arr

array([[[0.34746059, 0.54212558, 0.36484667],
        [0.61066205, 0.28423474, 0.35145902],
        [0.496585  , 0.58400684, 0.32484626]],

       [[0.9321284 , 0.79367594, 0.73152982],
        [0.96097169, 0.73217295, 0.03222368],
        [0.93348477, 0.12231459, 0.20328172]],

       [[0.88388518, 0.48229006, 0.72338558],
        [0.90261673, 0.493417  , 0.36371026],
        [0.60740966, 0.99723914, 0.76887405]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr=np.diag(np.arange(4)+1, k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4.Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.81979899, -1.15989682,  0.28745722,  1.09742719, -1.4183735 ],
       [ 1.50655918, -0.71495272,  0.5553433 , -1.30514078,  1.84864311],
       [ 0.5020348 ,  2.02319059, -1.64554728,  0.03270273,  1.18323988],
       [-0.04571077,  0.2696494 , -0.39444127, -0.18729575, -0.7842711 ],
       [-0.70716185, -0.12007171, -1.0393052 ,  0.58032951,  0.45539084]])

# 5.How to find common values between two arrays

In [10]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
np.intersect1d(arr1,arr2)

array([0, 1, 6, 7, 8])

# 6.How to get the dates of yesterday, today and tomorrow

In [11]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-01 2020-08-02 2020-08-03


# 7.Consider two random array A and B, check if they are equal

In [13]:
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
equal=np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')


Array1:
[[0.05798471 0.91583492 0.1137923 ]
 [0.50728452 0.11101415 0.69796042]
 [0.39349115 0.16780211 0.35142255]]


Array2:
[[0.50533059 0.1009771  0.57341216]
 [0.86850842 0.09306433 0.93629784]
 [0.32388341 0.84565949 0.4688991 ]]


Equality: False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [14]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.57012731, 0.35886356, 0.03718761, 0.        , 0.03553698,
       0.82262797, 0.87524437, 0.82904835, 0.25805495, 0.74442864])

# 9.How to print all the values of an array?

In [15]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [16]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 2.32053205e-01, -5.82818166e-02, -1.73771388e-01],
       [-1.29694912e-01,  3.76135894e-01, -2.46440982e-01],
       [-1.43424197e-04, -3.18798322e-01,  3.18941746e-01]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [17]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([4., 4., 4., 1., 2.])

# 12.How to get the diagonal of a dot product?

In [18]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([90, 95, 12])

# 13.How to find the most frequent value in an array?

In [19]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[2 1 1 1 1 6 4 0 4 5 6 4 7 4 3 5 4 3 0 3]


4

# 14.How to get the n largest values of an array

In [20]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

5

# 15.How to create a record array from a regular array?

In [21]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])